version: "3.9"

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
#      - tika
  elasticsearch:
    image: elasticsearch/elasticsearch:8.6.2
    build:
      context: ./
      dockerfile: Dockerfile-elasticsearch
    ports:
      - "9200:9200"
  kibana:
    image: kibana/kibana:8.6.2
    build:
      context: ./
      dockerfile: Dockerfile-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
#  tika:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "9998:9998"
